version: '3.8'

services:
  k4a-optimized:
    build: 
      context: .
      dockerfile: Dockerfile.optimized
    container_name: k4a_optimized_container
    runtime: nvidia
    environment:
      # NVIDIA GPU access (essential for OpenGL)
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # X11 forwarding for k4aviewer
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      # USB buffer optimization
      - USB_BUFFER_SIZE=1000MB
    volumes:
      # USB device access
      - /dev:/dev
      # X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Mount our test scripts
      - ./test_depth.py:/workspace/test_depth.py
      - ./run_kinect_host.sh:/workspace/run_kinect_host.sh
    privileged: true
    network_mode: host
    tty: true
    stdin_open: true
    command: bash
